apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apps-and-services.yaml
- backend-network-policy.yaml
- ingress-rules.yaml
- hpa-frontend.yaml

labels:
  - pairs:
      environment: local-dev
      managed-by: kustomize
    includeSelectors: false
